image: python:latest

before_script:
  - python -V

stages:
  - style
  - test

pep8:
  stage: style
  before_script:
    - pip install -r ci/pycodestyle_requirements.txt
  script:
    - ./ci/pycodestyle_runner.sh
  artifacts:
    paths:
      - public/pycodestyle.txt

pylint:
  stage: style
  before_script:
    - pip install -r ci/pylint_requirements.txt
  script:
    - ./ci/pylint_runner.sh
  artifacts:
    paths:
      - public/pylint.svg
      - public/pylint.html

api_test:
  stage: test
  before_script:
    - pip instal -r requirements.txt
  script:
    - python te./api
  artifacts:
    paths:
