"""empty message

Revision ID: cc7b8d94f35b
Revises: c1b87af90dbb
Create Date: 2020-03-21 14:04:41.947406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7b8d94f35b'
down_revision = 'c1b87af90dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('location', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'longitude')
    op.drop_column('location', 'latitude')
    # ### end Alembic commands ###
